# Generated by Django 4.2 on 2023-04-13 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorprofile',
            name='avatar_slug',
            field=models.URLField(max_length=500),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='avatar_slug',
            field=models.URLField(max_length=500),
        ),
    ]
