# Generated by Django 4.2 on 2023-04-13 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_doctorprofile_avatar_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='is_profile',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='is_profile',
            field=models.BooleanField(default=False),
        ),
    ]
