# Generated by Django 4.2 on 2023-04-13 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_doctorprofile_is_profile_patientprofile_is_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctorprofile',
            old_name='is_profile',
            new_name='is_complete',
        ),
        migrations.RenameField(
            model_name='patientprofile',
            old_name='is_profile',
            new_name='is_complete',
        ),
    ]
