# Generated by Django 4.2 on 2023-04-12 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_patientprofile_doctorprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientprofile',
            name='height',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='weight',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
