# Generated by Django 4.2 on 2023-04-13 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_is_profile_doctorprofile_is_complete_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='info',
            field=models.CharField(blank=True, max_length=220, null=True),
        ),
    ]
